name: Generate Notebook (PDF) + README.md

on:
  push:
    branches:
      - main
    paths:
      - 'algorithms/**'
      - 'theoretical/**'
  pull_request:
    branches:
      - main
    paths:
      - 'algorithms/**'
      - 'theoretical/**'

jobs:
  notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Notebook
        uses: addnab/docker-run-action@v3
        with:
            image: mateusvrs/cp-notebook:v1.0
            options: -w /usr/src/app -v ${{ github.workspace }}:/usr/src/app
            run: make team_name="An√µes do TLE"
      
      - name: Format Files (Clang) - Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          file_pattern: '*.cpp'

          commit_message: "clang(format): cpp files correct indentation"
      
      - name: Notebook Update - Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          file_pattern: 'notebook.pdf'

          commit_message: "notebook(pdf): update to latest version"

      - name: README Update - Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          file_pattern: 'README.md'

          commit_message: "docs(readme): update to match with notebook"
